# Generated by Django 2.0.13 on 2020-06-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r030', models.IntegerField(verbose_name='Код валюты')),
                ('cc', models.CharField(max_length=5, verbose_name='Код валюты буквенный')),
                ('txt', models.CharField(max_length=128, verbose_name='Название валюты')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Значение')),
                ('exchangedate', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курс валют',
            },
        ),
    ]
